# Minimum iOS 15 (modern baseline; compatible with current pods and Xcode 26 SDK)
platform :ios, '15.0'

target 'Conrra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '5.18.7'
  pod 'IQKeyboardManager','6.5.19'
  pod 'Firebase/Database', '10.22.0'
  pod 'Firebase/Messaging', '10.22.0'
  pod 'Firebase/Auth', '10.22.0'
  pod 'Firebase/Crashlytics', '10.22.0'
  pod 'Stripe'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'ReactiveObjC'
  pod 'ReactiveSwift', '~> 6.1'
  pod 'Firebase/Analytics', '10.22.0'
end

# Force all pods to iOS 15+ so Xcode doesn't try to link libarclite (removed in newer SDKs)
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
